version: '3'
services:
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_USER: ${DATABASE_USERNAME}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: openweather_homologacao
    env_file: ./.env
  rabbitmq:
    image: rabbitmq:3.9-management
    hostname: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
  api:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/code
    ports:
      - 5000:5000
    links:
      - db
    env_file: ./.env
  worker:
    restart: always
    build:
      context: .
    command: celery -A openweather.main.celery worker --events --concurrency=1 --loglevel=info
    volumes:
      - .:/code
    depends_on:
      - api
    links:
      - rabbitmq
    env_file: ./.env